# Generated by Django 3.1.7 on 2021-03-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
